version: '3.7'

services:
  postgres:
    image: 'postgres:14.5'
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - '/srv/postgres:/data/postgres'
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - '/srv/pgadmin:/var/lib/pgadmin'
    ports:
      - '${PGADMIN_PORT:-5050}:8080'
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: postegres-network
